// This file is @generated by prost-build.
/// Message containing options to specify how fake data should be generated to represent
/// the field.
/// For example, if you have a field called "id" which represents a user ID specified
/// by email address, you might provide something like the following in your proto file:
///       message User {
///         string id = 1 \[(gen_fake.field).data_type = "SafeEmail"\];
///         string name = 2 \[(gen_fake.field).data_type = "FirstName"\];
///         string family_name = 3 \[(gen_fake.field).data_type = "LastName"\];
///       }
/// where "SafeEmail", "FirstName", and "LastName" are all commands provided by the
/// `fake` library (crate). See <https://crates.io/crates/fake> for more information.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FakeDataFieldOption {
    /// A string providing the type of fake data to generate for the field.
    /// This plugin uses the Rust `fake` library (crate) to generate fake data, and for
    /// simplicity matches 1:1 the commands that the library provides as its CLI
    /// commands. For example, "CItyPrefix", "Isbn", "FilePath", etc.
    /// See <https://crates.io/crates/fake> for more information.
    #[prost(string, tag = "1")]
    pub data_type: ::prost::alloc::string::String,
}
