// This file is @generated by prost-build.
/// Message containing options to specify how fake data should be generated to represent
/// the field.
/// For example, if you have a field called "id" which represents a user ID specified
/// by email address, you might provide something like the following in your proto file:
///       message User {
///         string id = 1 \[(gen_fake.field).data_type = "SafeEmail"\];
///         string name = 2 \[(gen_fake.field).data_type = "FirstName"\];
///         string family_name = 3 \[(gen_fake.field).data_type = "LastName"\];
///       }
/// where "SafeEmail", "FirstName", and "LastName" are all commands provided by the
/// `fake` library (crate). See <https://crates.io/crates/fake> for more information.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FakeDataFieldOption {
    /// A string providing the type of fake data to generate for the field.
    /// This plugin uses the Rust `fake` library (crate) to generate fake data, and for
    /// simplicity matches 1:1 the commands that the library provides as its CLI
    /// commands. For example, "CItyPrefix", "Isbn", "FilePath", etc.
    /// See <https://crates.io/crates/fake> for more information.
    #[prost(string, tag = "1")]
    pub data_type: ::prost::alloc::string::String,
    /// Optional language code. The `fake` library, which this plugin uses to generate
    /// fake data, defines languages "<LANGUAGE>_<COUNTRY>" using all uppercase, such as
    /// "FR_FR", "PT_BR", etc. It also uses only "EN" (no country). Info can be found
    /// here: <https://docs.rs/fake/latest/fake/locales/index.html>
    /// This plugin accepts the language as lowercase or uppercase, accepts just the
    /// 2-letter language code, or the actual word, but written in English. Therefore,
    /// "ZH_CN", "zh_CN", or "Chinese" are all valid values to represent Chinese.
    #[prost(string, tag = "2")]
    pub language: ::prost::alloc::string::String,
    /// For repeated fields or optional fields, the minimum number of items to generate.
    /// If this is set to 0, the field will be allowed to be empty. Any value greater than
    /// 1 is equivalent to 1 for an optional field.
    /// If not set, the default is 1.
    #[prost(int32, tag = "3")]
    pub min_count: i32,
    /// For repeated fields, the maximum number of items to generate. Any value less than
    /// 1 is equivalent to 1. (Ie, the field cannot *always* be empty.)
    /// If not set, the default is 5.
    #[prost(int32, tag = "4")]
    pub max_count: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FakeDataMessageOption {
    /// If set to true, this message will be the one for which fake data is generated.
    /// If multiple messages have this set to true, only the first one will be used.
    #[prost(bool, tag = "1")]
    pub include: bool,
}
