// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 33.2
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `gen_fake/fake_field.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:gen_fake.FakeDataFieldOption)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct FakeDataFieldOption {
    // message fields
    // @@protoc_insertion_point(field:gen_fake.FakeDataFieldOption.data_type)
    pub data_type: ::std::string::String,
    // @@protoc_insertion_point(field:gen_fake.FakeDataFieldOption.language)
    pub language: ::std::string::String,
    // @@protoc_insertion_point(field:gen_fake.FakeDataFieldOption.min_count)
    pub min_count: i32,
    // @@protoc_insertion_point(field:gen_fake.FakeDataFieldOption.max_count)
    pub max_count: i32,
    // special fields
    // @@protoc_insertion_point(special_field:gen_fake.FakeDataFieldOption.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a FakeDataFieldOption {
    fn default() -> &'a FakeDataFieldOption {
        <FakeDataFieldOption as ::protobuf::Message>::default_instance()
    }
}

impl FakeDataFieldOption {
    pub fn new() -> FakeDataFieldOption {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data_type",
            |m: &FakeDataFieldOption| { &m.data_type },
            |m: &mut FakeDataFieldOption| { &mut m.data_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "language",
            |m: &FakeDataFieldOption| { &m.language },
            |m: &mut FakeDataFieldOption| { &mut m.language },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "min_count",
            |m: &FakeDataFieldOption| { &m.min_count },
            |m: &mut FakeDataFieldOption| { &mut m.min_count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "max_count",
            |m: &FakeDataFieldOption| { &m.max_count },
            |m: &mut FakeDataFieldOption| { &mut m.max_count },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<FakeDataFieldOption>(
            "FakeDataFieldOption",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for FakeDataFieldOption {
    const NAME: &'static str = "FakeDataFieldOption";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.data_type = is.read_string()?;
                },
                18 => {
                    self.language = is.read_string()?;
                },
                24 => {
                    self.min_count = is.read_int32()?;
                },
                32 => {
                    self.max_count = is.read_int32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.data_type.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.data_type);
        }
        if !self.language.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.language);
        }
        if self.min_count != 0 {
            my_size += ::protobuf::rt::int32_size(3, self.min_count);
        }
        if self.max_count != 0 {
            my_size += ::protobuf::rt::int32_size(4, self.max_count);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.data_type.is_empty() {
            os.write_string(1, &self.data_type)?;
        }
        if !self.language.is_empty() {
            os.write_string(2, &self.language)?;
        }
        if self.min_count != 0 {
            os.write_int32(3, self.min_count)?;
        }
        if self.max_count != 0 {
            os.write_int32(4, self.max_count)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> FakeDataFieldOption {
        FakeDataFieldOption::new()
    }

    fn clear(&mut self) {
        self.data_type.clear();
        self.language.clear();
        self.min_count = 0;
        self.max_count = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static FakeDataFieldOption {
        static instance: FakeDataFieldOption = FakeDataFieldOption {
            data_type: ::std::string::String::new(),
            language: ::std::string::String::new(),
            min_count: 0,
            max_count: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for FakeDataFieldOption {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("FakeDataFieldOption").unwrap()).clone()
    }
}

impl ::std::fmt::Display for FakeDataFieldOption {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FakeDataFieldOption {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:gen_fake.FakeDataMessageOption)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct FakeDataMessageOption {
    // message fields
    // @@protoc_insertion_point(field:gen_fake.FakeDataMessageOption.include)
    pub include: bool,
    // special fields
    // @@protoc_insertion_point(special_field:gen_fake.FakeDataMessageOption.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a FakeDataMessageOption {
    fn default() -> &'a FakeDataMessageOption {
        <FakeDataMessageOption as ::protobuf::Message>::default_instance()
    }
}

impl FakeDataMessageOption {
    pub fn new() -> FakeDataMessageOption {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "include",
            |m: &FakeDataMessageOption| { &m.include },
            |m: &mut FakeDataMessageOption| { &mut m.include },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<FakeDataMessageOption>(
            "FakeDataMessageOption",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for FakeDataMessageOption {
    const NAME: &'static str = "FakeDataMessageOption";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.include = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.include != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.include != false {
            os.write_bool(1, self.include)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> FakeDataMessageOption {
        FakeDataMessageOption::new()
    }

    fn clear(&mut self) {
        self.include = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static FakeDataMessageOption {
        static instance: FakeDataMessageOption = FakeDataMessageOption {
            include: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for FakeDataMessageOption {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("FakeDataMessageOption").unwrap()).clone()
    }
}

impl ::std::fmt::Display for FakeDataMessageOption {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FakeDataMessageOption {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Extension fields
pub mod exts {

    pub const fake_data: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, super::FakeDataFieldOption> = ::protobuf::ext::ExtFieldOptional::new(1491, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_MESSAGE);

    pub const fake_msg: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, super::FakeDataMessageOption> = ::protobuf::ext::ExtFieldOptional::new(1490, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_MESSAGE);
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x19gen_fake/fake_field.proto\x12\x08gen_fake\x1a\x20google/protobuf/d\
    escriptor.proto\"\x88\x01\n\x13FakeDataFieldOption\x12\x1b\n\tdata_type\
    \x18\x01\x20\x01(\tR\x08dataType\x12\x1a\n\x08language\x18\x02\x20\x01(\
    \tR\x08language\x12\x1b\n\tmin_count\x18\x03\x20\x01(\x05R\x08minCount\
    \x12\x1b\n\tmax_count\x18\x04\x20\x01(\x05R\x08maxCount\"1\n\x15FakeData\
    MessageOption\x12\x18\n\x07include\x18\x01\x20\x01(\x08R\x07include:Z\n\
    \tfake_data\x18\xd3\x0b\x20\x01(\x0b2\x1d.gen_fake.FakeDataFieldOption\
    \x12\x1d.google.protobuf.FieldOptionsR\x08fakeData:\\\n\x08fake_msg\x18\
    \xd2\x0b\x20\x01(\x0b2\x1f.gen_fake.FakeDataMessageOption\x12\x1f.google\
    .protobuf.MessageOptionsR\x07fakeMsgb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::descriptor::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(FakeDataFieldOption::generated_message_descriptor_data());
            messages.push(FakeDataMessageOption::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
